In [108]:
import numpy as np
import pandas as pd
import scipy.linalg


def dominant_eigen_value(M,tol=np.power(10.,-5),max_iter=5000):
    if(np.linalg.norm(M)<tol):
        return 0,np.ones([M.shape]) 
    u=np.random.normal(0,1,M.shape[1])
    u=u/np.linalg.norm(u)
    v=(M@u)
    v=v/np.linalg.norm(v)
    k=0
    while(np.linalg.norm(v-u)>tol):
        k=k+1
        u=v
        v=(M@v)
        v=v/np.linalg.norm(v)
        if k> max_iter:
            raise Exception("Failed to converge to an eigenvector")
    return v@(M@v),v

def eigen_decomposition(M,tol=np.power(10.,-8),max_iter=5000):
    eigenvectors=np.zeros(M.shape)
    eigenvalues=np.zeros(M.shape[1])
    K=scipy.linalg.null_space(M)
    ker_dim=K.shape[1]
    rank=M.shape[0]-ker_dim
    u=np.zeros(M.shape[1])
    for i in range(rank):
        u[i]=1
        if i>0:
            u[i-1]=0
            M=M-eigenvalues[i-1]*eigenvectors[:,i-1]*np.full(M.shape,eigenvectors[:,i-1]).T
        eigenvalues[i], eigenvectors[:,i]=dominant_eigen_value(M,tol,max_iter)
    eigenvalues[rank:M.shape[1]]=0
    eigenvectors[:,rank:M.shape[1]]=K
    return eigenvalues,eigenvectors
            
            


In [118]:
eigen_decomposition(np.array([[1,10],[0,1.1]]))

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide


(array([nan,  0.]),
 array([[nan, -1.],
        [nan,  0.]]))

In [119]:
scipy.linalg?

Type:        module
String form: <module 'scipy.linalg' from 'C:\\Anaconda\\lib\\site-packages\\scipy\\linalg\\__init__.py'>
File:        c:\anaconda\lib\site-packages\scipy\linalg\__init__.py
Docstring:  
Linear algebra (:mod:`scipy.linalg`)

.. currentmodule:: scipy.linalg

Linear algebra functions.

.. eventually, we should replace the numpy.linalg HTML link with just `numpy.linalg`

.. seealso::

   `numpy.linalg <https://www.numpy.org/devdocs/reference/routines.linalg.html>`__
   for more linear algebra functions. Note that
   although `scipy.linalg` imports most of them, identically named
   functions from `scipy.linalg` may offer more or slightly differing
   functionality.


Basics

.. autosummary::
   :toctree: generated/

   inv - Find the inverse of a square matrix
   solve - Solve a linear system of equations
   solve_banded - Solve a banded linear system
   solveh_banded - Solve a Hermitian or symmetric banded system
   solve_circulant - Solve a circulant system
   solve_t

In [67]:
np.full([2,2],[1,0]).T

array([[1, 1],
       [0, 0]])