In [2]:
import numpy as np

### 1. Notations & Definitions
$$\DeclareMathOperator{\id}{id}
\DeclareMathOperator{\im}{Im}
\DeclareMathOperator{\mat}{mat}
$$
### 1. Notations
- Let $\mathbb{K}\in \left\{\mathbb{R},\mathbb{C}\right\}$
- Let $E$ and $F$ be two finite dimensional inner product spaces over $\mathbb{K}$ with respective dimensions $n,m\in\mathbb{N}$
- We will denote by $\mu_f\in\mathbb{K}\left[x\right]$ the minimal polynomial over $\mathbb{K}$ of $f$
- We will denote by $\chi_f\in\mathbb{K}\left[x\right]$ the minimal polynomial over $\mathbb{K}$ of $f$
- We will denote for $f\in\mathscr{L}\left(H\right)$ by $H_{f,\lambda}=\ker\left(f-\lambda\id\right)$
- We will denote for $f\in\mathscr{L}\left(H\right)$ by $H_{f,\lambda,\alpha}=\ker\left(f-\lambda\id\right)^\alpha$
- We will denote by $\Pi_H$ the orthogonal projection on $H$

### 2. Definition of Moore-Penrose pseudoinverse
We call a Moore-Penrose inverse of a linear function  $f\in\mathscr{L}\left(E,F\right)$ every linear function  $\phi\in\mathscr{L}\left(F,E\right)$ satisfying:
1. $\phi\circ f\circ \phi=\phi$
2. $f\circ \phi\circ f=f$
3. $\phi\circ f,f\circ \phi$ are both self-adjoint operators

## 2. Relation between $\mu_{f\circ g}$ & $\mu_{g\circ f}$
$$ \mu_{f\circ g}=\sum_{i}a_ix^i \\
\implies \mu_{f\circ g}\left(f\circ g\right)=\sum_{i}a_i\left(f\circ g\right)^i\implies g\circ\mu_{f\circ g}\left(f\circ g\right)\circ f= \sum_{i}a_i g\circ\left(f\circ g\right)^i\circ f = \sum_{i}a_i \left(g\circ f\right)^{i+1}=0\\
\implies \mu_{g\circ f} \mid x\mu_{f\circ g}
$$
Also by symmetry, we have $\mu_{f\circ g} \mid x\mu_{g\circ f}$
We have then $$\begin{cases}1\le\deg \mu_{f\circ g} \le 1+\deg \mu_{g\circ f}\\
1 \le \deg \mu_{g\circ f} \le 1+\deg \mu_{f\circ g} 
\end{cases} \implies \deg \mu_{f\circ g}-\deg \mu_{g\circ f} \in \{-1,0,1\}
$$
### 2.1 $\deg \mu_{f\circ g}=1+\deg \mu_{g\circ f}$
We have $\begin{cases}\deg \mu_{f\circ g} = \deg x\mu_{g\circ f}\\
 \mu_{f\circ g}  \mid x \mu_{g\circ f} 
\end{cases}$ and both polynomials are monic, we have then $ \mu_{f\circ g}=x\mu_{g\circ f}$
### 2.2 $\deg \mu_{g\circ f}=1+\deg \mu_{f\circ g}$
we have: $ \mu_{g\circ f}=x\mu_{f\circ g}$
### 2.3 $\deg \mu_{f\circ g}=\deg \mu_{g\circ f}$
We have then 

## 3. Eigenspaces of $f\circ g$ & $g\circ f$
We will work for $\mathbb{K}=\mathbb{C}$
$f\in\mathscr{L}\left(E,F\right),g\in\mathscr{L}\left(F,E\right)$
Let $(\lambda_i)_i$ be the distinct eigenvalues of $g\circ f$ and $(\alpha_i)_i$ their respective geometric multiplicties.

We have: $$ \bigoplus_i E_{g\circ f,\lambda_i,\alpha_i}=\bigoplus_i \ker\left(g\circ f- \lambda_i \id \right)^{\alpha_i}$$
- Let $\lambda\in\mathbb{C}^*$ a non zero eigenvalue of $g\circ f$ with geometric multiplicity $\alpha$
- Let $\mathscr{B} = \left(u_1,\dots,u_p\right)$ a basis of $E_{g\circ f,\lambda,\alpha}$



## 4. Eigendecomposition of $f^*\circ f$ and  $f\circ f^*$ 
Without Loss of generality, we assume that $n \le m$
Because $f\circ f^*$ and $f^*\circ f$ are both self-adjoint operators, they are both diagonilisable
Let $\mathscr{B_1}=\left(u_1,\dots,u_m\right)$ an orthonormal basis of eigenvectors of $f^*\circ f$ with their respective eigenvalues $\left(\lambda_1,\dots,\lambda_m\right)$

Let $\mathscr{B_1}=\left(u_1,\dots,u_m\right)$ an orthonormal basis of eigenvectors of $f^*\circ f$ with their respective eigenvalues $\left(\lambda_1,\dots,\lambda_m\right)$

## 5. Existence & Uniqueness

### 5.1 Uniqueness by construction
Let $f\in \mathscr{L}\left(E,F\right)$ and $g$ a Moore-Penrose inverse of $f$
We have $g\circ f$ is self-adjoint, so it has an orthonormal basis of eigenvectors

let $\left(\lambda,u\right)$ an eigen value-vector couple of $g\circ f$
we have: 
$$f\circ g\circ f (u)= f(u)=f(\lambda u)=\lambda f(u)\\
\implies \lambda = 1 \text{ or } f(u)=0 \implies \lambda = 1 \text{ or } g\circ f(u)=\lambda u = 0  \implies \lambda \in \{0,1\}$$

We have $$\begin{cases} 
\ker f \subset \ker g\circ f \\
  \ker g\circ f \subset \ker f\circ g \circ f
\end{cases} \implies \begin{cases}
\ker f \subset \ker g\circ f \\
  \ker g\circ f \subset \ker f
\end{cases}\implies \ker g\circ f= \ker f$$

Since every eigenvalue $\lambda \in\{0,1\}$ and $g\circ f$ is self-adjoint, we have 
$$\begin{cases}
E = E_{g\circ f,0}\oplus E_{g\circ f,1}\\
E_{g\circ f,0}=\ker g\circ f = \ker f\\
E_{g\circ f,1}=E_{g\circ f,0}^\perp = \left(\ker f \right)^\perp
\end{cases}$$

Let $\mathscr{B}=\left(u_1,\dots,u_p\right)$ an orthonormal basis of $\ker f^\perp$.

Since $\mathscr{B}$ is a basis of $\ker f^\perp = E_{g\circ f,1}$ which is an eigenspace with $\lambda = 1 \neq 0$, we have then $f\left(\mathscr{B}\right)=\left(f(u_1),\dots,f(u_p)\right)$ is a basis of $F_{f\circ g,1}$
 
Furthermore, since $f\circ g$ and $g\circ f$ have the same non-zero eigenvalues, we have every eigenvalue $\lambda$ of $f\circ g$ is either $0$ or $1$ 
$$\begin{cases}
F = F_{f\circ g,0}\oplus F_{f\circ g,1}\\
F_{f\circ g,1}= f\left(\ker f ^\perp\right) = \im f\\
F_{f\circ g,0}=F_{f\circ g,1}^\perp = f\left(\ker f ^\perp\right)^\perp = \im f^\perp = \ker f\circ g = \ker g
\end{cases}$$

Now: 
$$\forall i \in \{1,\dots,p\},\quad g\left(f(u_i)\right)=g\circ f(u_i) = u_i\\
\forall x \in  \im f^\perp, \quad g(x)=0 
$$

After this construction, we can verify such $g$ if it exists, is unique

### 5.2 Existence

Let $r$ be the rank of $f$

We have $\dim \ker f^\perp= \dim E - \dim \ker f$, and by the rank-nullity theorem, we have 
$r = \dim \im f = \dim E - \dim \ker f$. 

So $f$ is an isomorphism from $\ker f^\perp$ to $\im f$

Let $\mathscr{B}=\left(u_1,\dots,u_n\right)$ an orthonormal basis of $E$ with:
1. $\mathscr{B}_1= \left(u_1,\dots,u_r\right)$ an orthonormal basis of $\ker f^\perp$
2. $\mathscr{B}_2= \left(u_{1+r},\dots,u_n\right)$ an orthonormal basis of $\ker f$

we have then $f\left(\mathscr{B_1}\right)$ is a basis of $\im f$

Let $\mathscr{D}=\left(v_1,\dots,v_m\right)$ an orthonormal basis of $F$ with:
1. $\mathscr{D}_1= \left(v_1,\dots,v_r\right)$ an orthonormal basis of $\im f$
2. $\mathscr{D}_2= \left(v_{1+r},\dots,u_m\right)$ an orthonormal basis of $\im f ^\perp$


Let $g\in \mathscr{L}\left(F,E\right)/ \quad \begin{cases}
g\circ f \left(\mathscr{B}_1\right)=\mathscr{B}_1 \\
\ker g = \im f^\perp
\end{cases}$

By construction, such $g$ is unique, and it is easy to prove that 
$$
g_{\mid \im f} = f_{\mid \ker f^\perp}^{-1} \\
\implies 
\begin{cases}
\forall x \in \ker f^\perp, \quad g\circ f(x)=g_{\mid \im f}\circ f_{\mid \ker f^\perp}(x)= x\\
\forall x=f(s) \in \im f,s\in \ker f^\perp,\quad f\circ g (x) = f\circ g \circ f(s)=f(s)=x 
\end{cases}
$$
So we have $$
\begin{cases}
    \mat(g\circ f,\mathscr{B})= 
    \begin{pmatrix}
        I_r & \boldsymbol{0}\\
        \boldsymbol{0} & \boldsymbol{0}
    \end{pmatrix}
    \\
    \mat(f\circ g,\mathscr{D})= 
    \begin{pmatrix}
        I_r & \boldsymbol{0}\\
        \boldsymbol{0} & \boldsymbol{0}
    \end{pmatrix}
\end{cases}
$$

now we verify that $g$ is a Moore-Penrose pseudoinverse of $f$
- $ \forall x=a+b,(a,b) \in \ker f\times \ker f^\perp, \quad f\circ g \circ f (x)= f\circ g \circ f (a) +  f\circ g \circ f (b)=   f(b) = f(b) + f(a) = f(x)$
- $ \forall \omega=\alpha+\beta,(\alpha,\beta) \in \im f\times \im f^\perp,\\
\quad g\circ f \circ g (\omega) = g\circ f \circ g (\alpha) +  g\circ f \circ g (\beta)=  g\circ f \circ g (\alpha) = g (\alpha) =g (\alpha)+g (\beta)=g(\omega) $
- since the matrice of $g\circ f$ in the orthonormal basis $\mathscr{B}$ is hermitian, we have $g\circ f$ is self-adjoint
- since the matrice of $f\circ g$ in the orthonormal basis $\mathscr{D}$ is hermitian, we have $f\circ g$ is self-adjoint

- Conclusion:
$g=f^+$ is the Moore-Penrose pseudoinverse of $f$

## 6. Calculating the pseudoinverse from the SVD
Let $M \in \mathbb{R}^{m\times n}$
Let $U\in \mathscr{U}(n),V\in \mathscr{U}(m)$ and $\Sigma \in \mathbb{R}^{m\times n}$ a diagonal matrix such that:
$$ M = U\Sigma V^*$$
We have the following equality:
$$ \begin{cases}
M^+= V\Sigma^+U^*\\
\Sigma^+\in \mathbb{R}^{n\times m} \text{ is diagonal}\\
\Sigma^+_{i,i} = \begin{cases}
    \frac{1}{\Sigma_{i,i}} \text{ if } \Sigma_{i,i} \neq 0 \\
    0
\end{cases}
\end{cases}
$$
In fact $\Sigma^+$ is pseudoinverse of $\Sigma$

## 7. Proprieties
Let $f\in\mathscr{L}\left(E,F\right)$
1. $(f^+)^+=f$
2. $\ker f^+ = \im f^\perp$
3. $f^+\circ f = \Pi_{\ker f^\perp}$
4. $f \circ f^+ = \Pi_{\ker (f^+)^\perp}=\Pi_{\im f}$
5. $f^*\circ f \circ f^+ =f^* $
6. $f^+\circ f \circ f^*= f^*$
7. if $f$ is injective $\iff \ker f = \{\boldsymbol{0}\}: \quad f^+=\left(f^*\circ f\right)^{-1}f^*$
8. if $f^*$ is injective $\iff \ker f^* = \im f ^\perp = \{\boldsymbol{0}\}\iff \im f = F \iff f$ is surjective: $f^+=f^* \circ \left(f\circ f^*\right)^{-1}$
## 8. Applications
### 8.1 Linear least-squares
### 8.2 Minimum norm solution to a linear system

In [2]:
M=np.random.normal(0,1,[5,8])


In [5]:
np.linalg.eig(np.linalg.pinv(M)@M)


(array([-2.54307003e-17,  1.00000000e+00,  1.00000000e+00, -6.21984137e-17,
         1.81786966e-17,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00]),
 array([[-0.62097469, -0.63870172, -0.50130372,  0.57140508, -0.43059727,
         -0.56080997,  0.48383989,  0.60314584],
        [-0.11488568,  0.08971696,  0.07883548, -0.03358621, -0.26112962,
          0.35491226, -0.00298979, -0.04740202],
        [-0.11559336,  0.48744983,  0.60604589,  0.14858841, -0.02313218,
          0.38650976, -0.7627385 , -0.38677664],
        [-0.57003302,  0.3510206 ,  0.26632744,  0.58093214, -0.3615896 ,
          0.23553017, -0.13637124, -0.21964313],
        [ 0.3010795 ,  0.13587481,  0.28539573, -0.16061199,  0.12430355,
          0.26322566, -0.05520717, -0.16754957],
        [-0.302208  ,  0.28743257,  0.27558355,  0.42012666,  0.19358585,
          0.43486656, -0.2210091 , -0.44079322],
        [-0.06128502, -0.11933758, -0.17967516,  0.31896403, -0.31482021,
         -0.09403791,  0.09486671,

In [4]:
A=np.random.normal(0,.1,[2,3])
B=np.random.normal(0,.1,[3,2])

In [45]:
µ,U=np.linalg.eig(A@B)
U

array([[-0.99961231,  0.37137461],
       [-0.02784311, -0.92848312]])

In [63]:
s,V=np.linalg.eig(B@A)

In [71]:
(B@U)/np.linalg.norm(B@U,axis=0)

array([[-0.06090264,  0.96750812],
       [ 0.8529017 , -0.05766297],
       [-0.51850704, -0.24617682]])

In [74]:
V

array([[-0.06090264,  0.96750812,  0.48994145],
       [ 0.8529017 , -0.05766297,  0.85911506],
       [-0.51850704, -0.24617682,  0.14791447]])