In [2]:
import numpy as np

In [1]:
def simplex(M,Z,C):
    n = Z.shape[0]
    m = M.shape[1]
    l = M.shape[0]
    V = np.r_[Z,np.zeros(m-n)]
    M = M.copy().astype(float)
    Z = Z.copy().astype(float)
    C = C .copy().astype(float)
    i=0
    while np.max(V) > 0:
        i =i+1
        p = V.argmax()
        for j in range(l):
            if np.abs(M[j,p]) > 0:
                C[j] = C[j] / M[j,p]
                M[j,:] = M[j,:] / M[j,p]
        q = np.ma.masked_array(C,mask=C<=0).argmin()
        K = M[q,:]
        M = M - K
        M[q,:]=K
        k = C[q]
        C = C - k
        C[q]=k
        print(M)
        print(C)
        V = V -V[p]*K
    for i in range(m):
        if V[i] < 0:
            w = np.zeros(m)
            w[i]=1
            M = np.r_[M,np.atleast_2d(w)]
    C = np.r_[C,np.zeros((V<0).sum())]
    return (np.linalg.pinv(M)@C)[:n]@Z

In [3]:
M = np.array([[1,9,1,0,0],[-3,-4,0,-1,0],[-3,1,0,0,1]])
C = np.array([4,-5,-1])
Z = np.array([4,1])

In [4]:
simplex(M,Z,C)

[[ 0.          9.33333333  1.          0.          0.33333333]
 [ 0.          1.66666667  0.          0.33333333  0.33333333]
 [ 1.         -0.33333333 -0.         -0.         -0.33333333]]
[3.66666667 1.33333333 0.33333333]
[[ 0.          1.          0.10714286  0.          0.03571429]
 [ 0.          0.         -0.10714286  0.2         0.16428571]
 [-3.          0.         -0.10714286  0.          0.96428571]]
[ 0.39285714  0.40714286 -1.39285714]
[[ 0.         28.          3.65217391 -1.2173913   0.        ]
 [ 0.          0.         -0.65217391  1.2173913   1.        ]
 [-3.11111111  0.          0.5410628  -1.2173913   0.        ]]
[ 8.52173913  2.47826087 -3.92270531]
[[ 0.          7.66666667  1.         -0.33333333  0.        ]
 [-0.         -7.66666667  0.         -1.53333333 -1.53333333]
 [-5.75       -7.66666667  0.         -1.91666667  0.        ]]
[ 2.33333333 -6.13333333 -9.58333333]


6.666666666666668